In [2]:
#Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd

# load the dataset

data = gutenberg.raw('shakespeare-hamlet.txt')

#save data to file
with open('hamlet.txt', 'w') as file:
    file.write(data)

[nltk_data] Downloading package gutenberg to C:\Users\Raja
[nltk_data]     Marthala\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [3]:
# Data Preprocessing

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

#load the dataset
with open('hamlet.txt', 'r') as file:
    text=file.read().lower()

#Tokenize the text-creating indexes for words
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index) + 1
total_words

4818

In [4]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [5]:
# Create input sequences
input_sequences = []
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(0, len(token_list)):
        n_grams_sequence = token_list[:i+1]
        input_sequences.append(n_grams_sequence)

In [6]:
input_sequences # sentences are converted into input sequence

[[1],
 [1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407],
 [407, 1182],
 [407, 1182, 63],
 [408],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18],
 [18, 66],
 [451],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408],
 [408, 407],
 [451],
 [451, 25],
 [408],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 

In [7]:
# Applying Pad Sequence
max_sequence_len = max([len(x) for x in input_sequences]) #consider max sentence length 
max_sequence_len

14

In [8]:
input_sequences=np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))
input_sequences # All sentences are same size

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]])

In [9]:
# create predictors and label
import tensorflow as tf
x,y = input_sequences[:,:-1], input_sequences[:,-1]


In [10]:
x

array([[   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]])

In [11]:
y

array([   1,  687,    4, ..., 1047,    4,  193])

In [12]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words) # converting output features to catergories
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [13]:
#Splitting dataset into Train and Test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [17]:
# Train LSTM RNN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout

#Define the model
model = Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1)) # 100 is number of dimensions for embeddings
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words, activation="softmax"))

#compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 13, 100)           481800    
                                                                 
 lstm_2 (LSTM)               (None, 13, 150)           150600    
                                                                 
 dropout_1 (Dropout)         (None, 13, 150)           0         
                                                                 
 lstm_3 (LSTM)               (None, 100)               100400    
                                                                 
 dense_1 (Dense)             (None, 4818)              486618    
                                                                 
Total params: 1219418 (4.65 MB)
Trainable params: 1219418 (4.65 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
# Define early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=350, restore_best_weights=True)

In [26]:
# Train the model

history = model.fit(x_train, y_train, epochs=400, verbose=1, validation_data=(x_test, y_test), callbacks=[early_stopping])

Epoch 1/400
743/743 [==============================] - 35s 47ms/step - loss: 2.7697 - accuracy: 0.4156 - val_loss: 11.0376 - val_accuracy: 0.0574
Epoch 2/400
743/743 [==============================] - 36s 49ms/step - loss: 2.7428 - accuracy: 0.4212 - val_loss: 11.1147 - val_accuracy: 0.0582
Epoch 3/400
743/743 [==============================] - 34s 46ms/step - loss: 2.7173 - accuracy: 0.4289 - val_loss: 11.1671 - val_accuracy: 0.0577
Epoch 4/400
743/743 [==============================] - 34s 45ms/step - loss: 2.6819 - accuracy: 0.4352 - val_loss: 11.2186 - val_accuracy: 0.0582
Epoch 5/400
743/743 [==============================] - 34s 46ms/step - loss: 2.6593 - accuracy: 0.4368 - val_loss: 11.3230 - val_accuracy: 0.0591
Epoch 6/400
743/743 [==============================] - 34s 46ms/step - loss: 2.6372 - accuracy: 0.4433 - val_loss: 11.3439 - val_accuracy: 0.0547
Epoch 7/400
743/743 [==============================] - 36s 48ms/step - loss: 2.6024 - accuracy: 0.4493 - val_loss: 11.4226 -

In [27]:
#Function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted=model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word

    return None

In [30]:
input_text = "But to recouer of vs by strong hand And termes"
print(f"input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model, tokenizer, input_text, max_sequence_len)
print(f"Next word prediction:{next_word}")

input text:But to recouer of vs by strong hand And termes
Next word prediction:water


In [22]:
#save the model
model.save('next_word_prediction_model.h5')

#save the tokernizer
import pickle
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

m:\Learning_Workspace\AI\AI_Projects\KrishNaikProjects\RNN-LSTM-GRU-Predicting-Next-Word\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
